/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pfj_io_uring_Uring */

#ifndef _Included_org_pfj_io_uring_Uring
#define _Included_org_pfj_io_uring_Uring
#ifdef __cplusplus
extern "C" {
#endif
#undef org_pfj_io_uring_Uring_SIZE
#define org_pfj_io_uring_Uring_SIZE 256LL
/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    init
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_init
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pfj_io_uring_Uring_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    peekCQ
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_peekCQ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    advanceCQ
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_pfj_io_uring_Uring_advanceCQ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    readyCQ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_readyCQ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    spaceLeft
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_pfj_io_uring_Uring_spaceLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    nextSQEntry
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_pfj_io_uring_Uring_nextSQEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    peekSQEntries
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_peekSQEntries
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    submitAndWait
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_pfj_io_uring_Uring_submitAndWait
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_socket
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_pfj_io_uring_Uring
 * Method:    prepareForListen
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_org_pfj_io_uring_Uring_prepareForListen
  (JNIEnv *, jclass, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
