name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21.0.69-ea'
          cache: 'maven'
      - name: Build with Maven
        run: sudo -E bash -c "ulimit -l 65536 && ulimit -a && MAVEN_OPTS=--enable-preview mvn --no-transfer-progress --batch-mode --update-snapshots package"
