name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: sudo env "PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH" bash -c "ulimit -l 65536 && ulimit -a && echo $PATH && ls -l $JAVA_HOME && ls -l $JAVA_HOME/bin && java -version && ./mvnw --no-transfer-progress --batch-mode --update-snapshots package"
