name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: bash -c "ulimit -l 65536 && ulimit -a && mvn --no-transfer-progress --batch-mode --update-snapshots package"
