name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx1024m
        run: mvn --batch-mode --update-snapshots verify
